### ISSUE TITLE
Join Biolisp!

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [slyrus/cl-bio#1]
Would you be interested in hosting your repo in this organization: https://github.com/biolisp

**Comment by slyrus** [comment]
I'm not necessarily opposed, but tell me more about biolisp. Is this related to the Stanford biobike stuff?

**Comment by Bohdan-Khomtchouk** [comment]
No, BioBIKE would also be under the Biolisp umbrella.  I'm trying to bring together all bio-related Lisp repositories under the same organization in order to establish a public-facing community effort.  In the spirit of eating your own dog food, I'm migrating [Biochat](https://github.com/Bohdan-Khomtchouk/Biochat) to https://github.com/biolisp once the manuscript is published.  Perhaps even sooner, depending on permissions from my grant funding source.

**Comment by Bohdan-Khomtchouk** [comment]
Just want to add that the purpose is to have a public Bioconductor/Biopython style repository dedicated to Lisp programming in biology (Biolisp).  Without something like this, there is no official package ecosystem/community.

**Comment by Bohdan-Khomtchouk** [comment]
I forked your repo to https://github.com/biolisp
